sudo: false
language: node_js
node_js:
  - v0.10
  - v0.12
  - v4
  - v5
  - v6

install:
    - npm install -g eslint mocha grunt-cli
    - npm install

script:
    - eslint "app/*.js" "casper/*.js" "theme/*.js" "test/*.js"
    - npm test
